# Generated by Django 4.1.7 on 2024-04-24 03:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='end',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='availability',
            name='start',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
