# Generated by Django 5.0.3 on 2024-04-25 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_user_profile_image'),
        ('users', '0014_alter_availability_end_alter_availability_start'),
    ]

    operations = [
    ]
