# Generated by Django 5.0.3 on 2024-05-01 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_user_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='image',
            new_name='imageP',
        ),
    ]
