# Generated by Django 4.1.7 on 2024-05-13 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_rename_imagep_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='personal_description',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
