# Generated by Django 5.0.3 on 2024-05-20 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_user_personal_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='friend',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
