# Generated by Django 5.0.3 on 2024-05-18 23:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_chat_user_chat_recipientname_chat_sendername'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='recipientName',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='senderName',
        ),
        migrations.AddField(
            model_name='chat',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='user_chats', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
