# Generated by Django 5.0.3 on 2024-04-24 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0013_alter_rent_outfit_delete_outfit_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='status',
            field=models.CharField(default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='rent',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='rent',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rent.event'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='outfit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rent.outfit'),
        ),
    ]
