# Generated by Django 5.0.3 on 2024-05-19 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0014_rent_status_alter_rent_description_alter_rent_event_and_more'),
        ('users', '0025_alter_user_personal_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientComent',
            fields=[
                ('id_comment', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=200)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.client')),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.friend')),
                ('rent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent.rent')),
            ],
        ),
    ]
