# Generated by Django 5.0.3 on 2024-05-18 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='user',
        ),
        migrations.AddField(
            model_name='chat',
            name='recipientName',
            field=models.CharField(default='Unknown Recipient', max_length=250),
        ),
        migrations.AddField(
            model_name='chat',
            name='senderName',
            field=models.CharField(default='Unknown Sender', max_length=250),
        ),
    ]
