# Generated by Django 5.0.3 on 2024-04-21 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_taste_like_rename_user_taste_user_like_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='user_id',
            new_name='user',
        ),
    ]
