# Generated by Django 4.1.7 on 2024-04-27 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_user_image_alter_availability_dia_semana'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
